// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParckingAuto.Data;

#nullable disable

namespace ParckingAuto.Migrations
{
    [DbContext(typeof(ParcAutoContext))]
    [Migration("20260629165539_ChauffeurRelationsFix")]
    partial class ChauffeurRelationsFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ParckingAuto.Models.Alerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAlerte")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferenceDeclencheur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeAlerte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Alertes");
                });

            modelBuilder.Entity("ParckingAuto.Models.Carburant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePlein")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("int");

                    b.Property<decimal>("VolumeLitres")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Carburants");
                });

            modelBuilder.Entity("ParckingAuto.Models.Chauffeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PermisExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PermisNumero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Chauffeurs");
                });

            modelBuilder.Entity("ParckingAuto.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fichier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ParckingAuto.Models.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cout")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DateIntervention")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Facture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KilometrageIntervention")
                        .HasColumnType("int");

                    b.Property<string>("TypeIntervention")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("ParckingAuto.Models.Mouvement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChauffeurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDepart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateRetour")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KmDepart")
                        .HasColumnType("int");

                    b.Property<int?>("KmRetour")
                        .HasColumnType("int");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChauffeurId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Mouvements");
                });

            modelBuilder.Entity("ParckingAuto.Models.Parametres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("NotifAssurance")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NotifPermis")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NotifVidange")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NotifVisiteTech")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Parametres");
                });

            modelBuilder.Entity("ParckingAuto.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ParckingAuto.Models.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneeFabrication")
                        .HasColumnType("int");

                    b.Property<int>("AnneeMiseEnCirculation")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssuranceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("AssuranceDateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssuranceReference")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompagnieAssurance")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Constructeur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DatePremiereMiseEnCirculation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DernierKmVidange")
                        .HasColumnType("int");

                    b.Property<string>("GenreVehicule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("int");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NombrePlaces")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCarteGrise")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroChassis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProchaineVisite")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PuissanceFiscale")
                        .HasColumnType("int");

                    b.Property<string>("TypeCarburant")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsageVehicule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("VisiteTechniqueDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Vehicules");
                });

            modelBuilder.Entity("ParckingAuto.Models.Alerte", b =>
                {
                    b.HasOne("ParckingAuto.Models.Vehicule", "Vehicule")
                        .WithMany()
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("ParckingAuto.Models.Carburant", b =>
                {
                    b.HasOne("ParckingAuto.Models.Vehicule", "Vehicule")
                        .WithMany()
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("ParckingAuto.Models.Chauffeur", b =>
                {
                    b.HasOne("ParckingAuto.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ParckingAuto.Models.Document", b =>
                {
                    b.HasOne("ParckingAuto.Models.Vehicule", "Vehicule")
                        .WithMany()
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("ParckingAuto.Models.Maintenance", b =>
                {
                    b.HasOne("ParckingAuto.Models.Vehicule", "Vehicule")
                        .WithMany()
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("ParckingAuto.Models.Mouvement", b =>
                {
                    b.HasOne("ParckingAuto.Models.Chauffeur", "Chauffeur")
                        .WithMany()
                        .HasForeignKey("ChauffeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParckingAuto.Models.Vehicule", "Vehicule")
                        .WithMany()
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chauffeur");

                    b.Navigation("Vehicule");
                });
#pragma warning restore 612, 618
        }
    }
}
